### ISSUE TITLE
AttributeErorr: 'NoneType' object has no attribute 'setsize' when attempting txt2img

### ISSUE THREAD

**Issue by InconsolableCellist** [sddebz/stable-diffusion-krita-plugin#24]
A NoneType error occurs when trying to use txt2img. The images are generated on the server in the `outputs/krita-out` directory

## System

```
$ cat /etc/os-release
PRETTY_NAME="Devuan GNU/Linux 4 (chimaera)"
NAME="Devuan GNU/Linux"
VERSION_ID="4"
VERSION="4 (chimaera)"
VERSION_CODENAME="chimaera"
ID=devuan
ID_LIKE=debian
HOME_URL="https://www.devuan.org/"
SUPPORT_URL="https://devuan.org/os/community"
BUG_REPORT_URL="https://bugs.devuan.org/"
```

```
$ krita --version
Replacing libstdc++.so.6 with the fallback version: libstdc++.so.6.0.28 -> libstdc++.so.6.0.29
krita 5.1.0
```

## Steps to reproduce

1. Follow the installation steps on https://github.com/sddebz/stable-diffusion-krita-plugin, Windows 10 server, Linux client
2. Adjust the krita_server.py to bind to the localhost name (might be the same to just hardcore the LAN IP)
3. Launch the server and Krita on the client
4. Direct the client to connect to the server via the LAN IP
5. Create a new image, 512x512 pixels. Draw briefly with a brush
6. Enter "A cat" in the txt2img panel of the SD plugin docker, leave other settings default
7. Hit `Apply text2img`

## Observed behavior

Server begins generating the image and finishes. Produces a file in `outputs/krita-out`. A script error pops up in a new window in Krita:

```
AttributeError
Python 3.8.1: /usr/bin/python3
Fri Sep  9 19:56:31 2022

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 /home/user/.local/share/krita/pykrita/krita_diff/krita_diff_ui.py in <lambda>()
  229         )
  230         self.txt2img_start_button.released.connect(
  231             lambda: script.action_txt2img()
  232         )
  233 
global script = <krita_diff.krita_diff.Script object>
script.action_txt2img = <bound method Script.action_txt2img of <krita_diff.krita_diff.Script object>>

 /home/user/.local/share/krita/pykrita/krita_diff/krita_diff.py in action_txt2img(self=<krita_diff.krita_diff.Script object>)
  329         self.update_config()
  330         self.try_fix_aspect_ratio()
  331         self.apply_txt2img()
  332         self.create_mask_layer_workaround()
  333 
self = <krita_diff.krita_diff.Script object>
self.apply_txt2img = <bound method Script.apply_txt2img of <krita_diff.krita_diff.Script object>>

 /home/user/.local/share/krita/pykrita/krita_diff/krita_diff.py in apply_txt2img(self=<krita_diff.krita_diff.Script object>)
  267         print(f"Getting images: {outputs}")
  268         for i, output in enumerate(outputs):
  269             self.insert_img(f"txt2img {i + 1}: {os.path.basename(output)}", output, i + 1 == len(outputs))
  270         self.clear_temp_images(outputs)
  271         self.doc.refreshProjection()
self = <krita_diff.krita_diff.Script object>
self.insert_img = <bound method Script.insert_img of <krita_diff.krita_diff.Script object>>
output = r'F:\git\stable-diffusion-krita-plugin\outputs\krita-out\1662774991_0.png'
i = 0
builtinlen = <built-in function len>
outputs = [r'F:\git\stable-diffusion-krita-plugin\outputs\krita-out\1662774991_0.png']

 /home/user/.local/share/krita/pykrita/krita_diff/krita_diff.py in insert_img(self=<krita_diff.krita_diff.Script object>, layer_name=r'txt2img 1: F:\git\stable-diffusion-krita-plugin\outputs\krita-out\1662774991_0.png', path=r'F:\git\stable-diffusion-krita-plugin\outputs\krita-out\1662774991_0.png', visible=True)
  253         image = QImage()
  254         image.load(path, "PNG")
  255         ba = self.image_to_ba(image)
  256 
  257         layer = self.create_layer(layer_name)
ba undefined
self = <krita_diff.krita_diff.Script object>
self.image_to_ba = <bound method Script.image_to_ba of <krita_diff.krita_diff.Script object>>
image = <PyQt5.QtGui.QImage object>

 /home/user/.local/share/krita/pykrita/krita_diff/krita_diff.py in image_to_ba(self=<krita_diff.krita_diff.Script object>, image=<PyQt5.QtGui.QImage object>)
  247     def image_to_ba(self, image):
  248         ptr = image.bits()
  249         ptr.setsize(image.byteCount())
  250         return QByteArray(ptr.asstring())
  251 
ptr = None
ptr.setsize undefined
image = <PyQt5.QtGui.QImage object>
image.byteCount = <built-in method byteCount of QImage object>
AttributeError: 'NoneType' object has no attribute 'setsize'
    __cause__ = None
    __class__ = <class 'AttributeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AttributeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AttributeError object>
    __doc__ = 'Attribute not found.'
    __eq__ = <method-wrapper '__eq__' of AttributeError object>
    __format__ = <built-in method __format__ of AttributeError object>
    __ge__ = <method-wrapper '__ge__' of AttributeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AttributeError object>
    __gt__ = <method-wrapper '__gt__' of AttributeError object>
    __hash__ = <method-wrapper '__hash__' of AttributeError object>
    __init__ = <method-wrapper '__init__' of AttributeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AttributeError object>
    __lt__ = <method-wrapper '__lt__' of AttributeError object>
    __ne__ = <method-wrapper '__ne__' of AttributeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AttributeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AttributeError object>
    __repr__ = <method-wrapper '__repr__' of AttributeError object>
    __setattr__ = <method-wrapper '__setattr__' of AttributeError object>
    __setstate__ = <built-in method __setstate__ of AttributeError object>
    __sizeof__ = <built-in method __sizeof__ of AttributeError object>
    __str__ = <method-wrapper '__str__' of AttributeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ("'NoneType' object has no attribute 'setsize'",)
    with_traceback = <built-in method with_traceback of AttributeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "/home/user/.local/share/krita/pykrita/krita_diff/krita_diff_ui.py", line 231, in <lambda>
    lambda: script.action_txt2img()
  File "/home/user/.local/share/krita/pykrita/krita_diff/krita_diff.py", line 331, in action_txt2img
    self.apply_txt2img()
  File "/home/user/.local/share/krita/pykrita/krita_diff/krita_diff.py", line 269, in apply_txt2img
    self.insert_img(f"txt2img {i + 1}: {os.path.basename(output)}", output, i + 1 == len(outputs))
  File "/home/user/.local/share/krita/pykrita/krita_diff/krita_diff.py", line 255, in insert_img
    ba = self.image_to_ba(image)
  File "/home/user/.local/share/krita/pykrita/krita_diff/krita_diff.py", line 249, in image_to_ba
    ptr.setsize(image.byteCount())
AttributeError: 'NoneType' object has no attribute 'setsize'

 ```

## Expected Behavior

The generated image appears in Krita

**Comment by InconsolableCellist** [comment]
It appears the plugin requires the image generation server to be on the same computer that Krita's running on. Can the webui not return the image results as part of the request?

**Comment by HWiese1980** [comment]
I have the webui running in WSL2, which should work. Unfortunately I'm getting this exact error. Is there a fix for this already? Issue is still open...
