### ISSUE TITLE
AttributeError: 'HTTPResponse' object has no attribute 'characters_written'

### ISSUE THREAD

**Issue by joxeankoret** [sddebz/stable-diffusion-krita-plugin#9]
Hi! I'm getting the following error running it under Linux and I don't understand why:

```Error in sys.excepthook:
Traceback (most recent call last):
  File "/tmp/.mount_krita-63aZkG/usr/lib/krita-python-libs/krita/excepthook.py", line 27, in on_error
    dlg = ExceptHookDialog(exc_type, exc_obj, exc_tb)
  File "/tmp/.mount_krita-63aZkG/usr/lib/krita-python-libs/krita/excepthook.py", line 64, in __init__
    html = cgitb.text((exc_type, exc_obj, exc_tb))
  File "/tmp/.mount_krita-63aZkG/usr/lib/python3.8/cgitb.py", line 247, in text
    value = pydoc.text.repr(getattr(evalue, name))
  File "/tmp/.mount_krita-63aZkG/usr/lib/python3.8/tempfile.py", line 469, in __getattr__
    a = getattr(file, name)
AttributeError: 'HTTPResponse' object has no attribute 'characters_written'

Original exception was:
Traceback (most recent call last):
  File "/home/joxean/.local/share/krita/pykrita/krita_diff/krita_diff.py", line 500, in <lambda>
    lambda: script.action_txt2img()
  File "/home/joxean/.local/share/krita/pykrita/krita_diff/krita_diff.py", line 277, in action_txt2img
    self.apply_txt2img()
  File "/home/joxean/.local/share/krita/pykrita/krita_diff/krita_diff.py", line 224, in apply_txt2img
    response = self.txt2img()
  File "/home/joxean/.local/share/krita/pykrita/krita_diff/krita_diff.py", line 110, in txt2img
    return self.post(self.cfg('base_url', str) + '/txt2img', params)
  File "/home/joxean/.local/share/krita/pykrita/krita_diff/krita_diff.py", line 90, in post
    with urllib.request.urlopen(req, body_encoded) as res:
  File "/tmp/.mount_krita-63aZkG/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/tmp/.mount_krita-63aZkG/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/tmp/.mount_krita-63aZkG/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/tmp/.mount_krita-63aZkG/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/tmp/.mount_krita-63aZkG/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/tmp/.mount_krita-63aZkG/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found```

The server is accesible, I have verified it (and, also, getting `/config` works). Any idea?

Thanks in advance!

**Comment by joxeankoret** [comment]
The problem was me all alone: I was running webui.py instead of krita_server.py. My apologies, and thank you for the plugin!
